from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ToolRequest(BaseModel):
    """The wire-format request the Merchant Agent Core sends to the Java
    Tool Layer for a single tool call.

    This is the Communication Contract's request shape - it is NOT the
    same thing as the Java Tool Layer's internal
    com.ecommerce.tools.model.ToolRequest, which is AgentTool.execute()'s
    in-process parameter object (userId + a parameters map). The Tool
    Layer's HTTP boundary is responsible for translating one into the
    other; this class contains no HTTP, execution, or business logic
    itself - it is data only, and has no dependency on FastAPI or the
    agent's reasoning/planning code.

    requestId - unique per call. Generated by the Agent Core (not by this
                class), and echoed back unchanged on
                ToolResponse.requestId for tracing/correlation - this is
                what lets multiple in-flight tool calls be told apart.
    toolName  - canonical tool name (e.g. "search_products"). The contract
                intentionally does not enumerate known tool names, so new
                tools work with this same request shape without any
                contract change.
    arguments - tool-specific parameters. Opaque to the contract; only the
                target tool's own input schema gives these meaning.
    context   - optional, extensible execution metadata. Conventional keys
                in use today: userId, sessionId, conversationId, tenantId,
                locale, currency - but no fixed schema is enforced here on
                purpose (see contracts/README.md).
    """

    model_config = ConfigDict(populate_by_name=True)

    request_id: str = Field(..., min_length=1, alias="requestId")
    tool_name: str = Field(..., min_length=1, alias="toolName")
    arguments: dict[str, Any] = Field(default_factory=dict)
    context: dict[str, Any] = Field(default_factory=dict)
