package com.ecommerce.tools.contract;

import jakarta.validation.constraints.NotBlank;

import java.util.Collections;
import java.util.Map;

/**
 * The wire-format request the Merchant Agent Core sends to the Java Tool
 * Layer for a single tool call.
 *
 * This is the Communication Contract's request shape - it is NOT the same
 * thing as com.ecommerce.tools.model.ToolRequest, which is
 * AgentTool.execute()'s internal, in-process parameter object (userId + a
 * parameters map). The Tool Layer's HTTP boundary (AgentToolController) is
 * responsible for translating one into the other; this class contains no
 * HTTP, execution, or business logic itself - it is data only.
 *
 * requestId - unique per call. Generated by the Agent Core (not by this
 *             class), and echoed back unchanged on
 *             ToolResponse.requestId for tracing/correlation - this is
 *             what lets multiple in-flight tool calls be told apart.
 * toolName  - canonical tool name (e.g. "search_products"). The contract
 *             intentionally does not enumerate known tool names, so new
 *             tools work with this same request shape without any
 *             contract change.
 * arguments - tool-specific parameters. Opaque to the contract; only the
 *             target tool's own input schema gives these meaning.
 * context   - optional, extensible execution metadata. Conventional keys
 *             in use today: userId, sessionId, conversationId, tenantId,
 *             locale, currency - but no fixed schema is enforced here on
 *             purpose (see the Communication Contract documentation).
 */
public class ToolRequest {

    @NotBlank(message = "requestId is required")
    private String requestId;

    @NotBlank(message = "toolName is required")
    private String toolName;

    private Map<String, Object> arguments = Collections.emptyMap();

    private Map<String, Object> context = Collections.emptyMap();

    public ToolRequest() {
    }

    public ToolRequest(String requestId, String toolName, Map<String, Object> arguments, Map<String, Object> context) {
        this.requestId = requestId;
        this.toolName = toolName;
        this.arguments = arguments == null ? Collections.emptyMap() : arguments;
        this.context = context == null ? Collections.emptyMap() : context;
    }

    public String getRequestId() {
        return requestId;
    }

    public void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    public String getToolName() {
        return toolName;
    }

    public void setToolName(String toolName) {
        this.toolName = toolName;
    }

    public Map<String, Object> getArguments() {
        return arguments;
    }

    public void setArguments(Map<String, Object> arguments) {
        this.arguments = arguments == null ? Collections.emptyMap() : arguments;
    }

    public Map<String, Object> getContext() {
        return context;
    }

    public void setContext(Map<String, Object> context) {
        this.context = context == null ? Collections.emptyMap() : context;
    }
}
